# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 04:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True)),
                ('pco', models.BooleanField(default=False)),
                ('volunteer', models.BooleanField(default=False)),
                ('delegate', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[(None, b'-'), (b'email', b'Email'), (b'voicemail', b'Voicemail'), (b'will-walk', b'Will Walk'), (b'picked-up-packet', b'Has Packet'), (b'walked', b'Walked'), (b'data-entered', b'Data Entered'), (b'will-not-walk', b'Will Not Walk')], default=None, max_length=32, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('mini_van', models.BooleanField(default=True, verbose_name=b'MiniVAN')),
            ],
            options={
                'ordering': ('precinct__long_name', 'status', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=4)),
                ('county_code', models.CharField(choices=[(b'AD', b'Adams'), (b'AS', b'Asotin'), (b'BE', b'Benton'), (b'CH', b'Chelan'), (b'CM', b'Clallam'), (b'CR', b'Clark'), (b'CU', b'Columbia'), (b'CZ', b'Cowlitz'), (b'DG', b'Douglas'), (b'FE', b'Ferry'), (b'FR', b'Franklin'), (b'GA', b'Garfield'), (b'GR', b'Grant'), (b'GY', b'Grays Harbor'), (b'IS', b'Island'), (b'JE', b'Jefferson'), (b'KI', b'King'), (b'KP', b'Kitsap'), (b'KS', b'Kittitas'), (b'KT', b'Klickitat'), (b'LE', b'Lewis'), (b'LI', b'Lincoln'), (b'MA', b'Mason'), (b'OK', b'Okanogan'), (b'PA', b'Pacific'), (b'PE', b'Pend Oreille'), (b'PI', b'Pierce'), (b'SJ', b'San Juan'), (b'SK', b'Skagit'), (b'SM', b'Skamania'), (b'SN', b'Snohomish'), (b'SP', b'Spokane'), (b'ST', b'Stevens'), (b'TH', b'Thurston'), (b'WK', b'Wahkiakum'), (b'WL', b'Walla Walla'), (b'WM', b'Whatcom'), (b'WT', b'Whitman'), (b'XX', b'Statewide'), (b'YA', b'Yakima')], max_length=2)),
                ('st_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='precinct',
            unique_together=set([('code', 'county_code')]),
        ),
        migrations.AddField(
            model_name='person',
            name='precinct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gotmfv.Precinct'),
        ),
        migrations.AddField(
            model_name='committee',
            name='precincts',
            field=models.ManyToManyField(blank=True, to='gotmfv.Precinct'),
        ),
        migrations.AddField(
            model_name='area',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotmfv.Committee'),
        ),
        migrations.AddField(
            model_name='area',
            name='point_person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='precincts',
            field=models.ManyToManyField(blank=True, to='gotmfv.Precinct'),
        ),
    ]
