# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotmfv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('precinct', 'status', 'full_name')},
        ),
        migrations.AddField(
            model_name='committee',
            name='people',
            field=models.ManyToManyField(blank=True, to='gotmfv.Person'),
        ),
        migrations.AlterField(
            model_name='area',
            name='point_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='pco',
            field=models.BooleanField(default=False, verbose_name=b'PCO'),
        ),
    ]
