# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotmfv', '0002_auto_20171009_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_status', models.CharField(blank=True, choices=[(None, b'-'), (b'email', b'Email'), (b'voicemail', b'Voicemail'), (b'will-walk', b'Will Walk'), (b'picked-up-packet', b'Has Packet'), (b'walked', b'Walked'), (b'data-entered', b'Data Entered'), (b'will-not-walk', b'Will Not Walk')], default=None, max_length=32, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotmfv.Area')),
            ],
        ),
        migrations.AlterField(
            model_name='committee',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='committees', to='gotmfv.Person'),
        ),
    ]
